openapi: 3.0.3
info:
  description: "___\nThis is the REST API for controlling the BrowserUp Proxy. \n\
    The BrowserUp Proxy is a swiss army knife for automated testing.\nIt allows traffic\
    \ capture in HAR files and manipulation. \nIt is also useful for Selenium/Cypress\
    \ tests.\n___\n"
  title: BrowserUp Proxy
  version: 1.0.0
servers:
- description: The development API server
  url: http://localhost:{port}/
  variables:
    port:
      default: "8080"
      enum:
      - "8080"
tags:
- description: BrowserUp Proxy REST API
  name: BrowserUp Proxy API
paths:
  /har:
    get:
      description: Get the current HAR.
      operationId: getHarLog
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    put:
      description: Starts a fresh HAR capture session.
      operationId: resetHarLog
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
  /har/page:
    put:
      description: Starts a fresh HAR Page in the current active HAR
      operationId: setHarPage
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
  /auth_basic/{domain}:
    delete:
      description: Clears Basic Auth for a domain, disabling Automatic Basic Auth
        for it.
      operationId: clearBasicAuthSettings
      parameters:
      - description: The domain for which to clear the basic auth settings
        explode: false
        in: path
        name: domain
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The current Basic Authorization setting is cleared and no longer
            used for requests to a domain.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    post:
      description: Enables automatic basic auth for a domain
      operationId: setBasicAuth
      parameters:
      - description: The domain for which this Basic Auth should be used
        explode: false
        in: path
        name: domain
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthBasic'
      responses:
        "204":
          description: Success!
      tags:
      - BrowserUpProxy
      x-contentType: application/json
      x-accepts: application/json
  /allowlist:
    delete:
      description: Clears the AllowList, which will turn-off allowlist based filtering
      operationId: clearAllowList
      responses:
        "204":
          description: The allowlist was cleared and allowlist-based filtering is
            OFF until a new list is posted.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    get:
      description: Get an AllowList
      operationId: getAllowList
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllowList'
          description: The current allowlist. Only allowed requests will pass through.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    post:
      description: Sets an AllowList
      operationId: setAllowList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllowList'
      responses:
        "204":
          description: Success!
      tags:
      - BrowserUpProxy
      x-contentType: application/json
      x-accepts: application/json
  /blocklist:
    get:
      description: Get a blocklist
      operationId: getBlockList
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockList'
          description: The current blocklist.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    post:
      description: Sets an BlockList
      operationId: setBlockList
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockList'
      responses:
        "204":
          description: Success!
      tags:
      - BrowserUpProxy
      x-contentType: application/json
      x-accepts: application/json
  /additional_headers:
    delete:
      description: Clear the additional Headers
      operationId: clearAdditionalHeaders
      responses:
        "204":
          description: The current additional header settings were cleared.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    get:
      description: Get the current added Headers
      operationId: getAdditionalHeaders
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Headers'
          description: The current header settings.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
    post:
      description: Set additional headers to add to requests
      operationId: setAdditionalHeaders
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Headers'
          description: Show the current additional header settings.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
  /healthcheck:
    get:
      description: Get the healthcheck
      responses:
        "200":
          description: OK means all is well.
      tags:
      - BrowserUpProxy
      x-accepts: application/json
components:
  schemas:
    entry:
      example:
        startedDateTime: 2000-01-23T04:56:07.000+00:00
        request:
          headers:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          httpVersion: httpVersion
          method: method
          headersSize: 5
          bodySize: 5
          comment: comment
          queryString:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          postData: '{}'
          url: https://openapi-generator.tech
          cookies:
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
        cache: '{}'
        response:
          headers:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          httpVersion: httpVersion
          redirectURL: redirectURL
          statusText: statusText
          headersSize: 3
          bodySize: 2
          comment: comment
          cookies:
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          content:
            size: 7
            comment: comment
            mimeType: mimeType
            text: text
            compression: 9
            encoding: encoding
          status: 2
        serverIPAddress: serverIPAddress
        timings: '{}'
        connection: connection
        comment: comment
        time: 0.14658129805029452
        pageref: pageref
      properties:
        pageref:
          type: string
        startedDateTime:
          format: date-time
          pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))
          type: string
        time:
          minimum: 0
          type: number
        request:
          $ref: '#/components/schemas/entry_request'
        response:
          $ref: '#/components/schemas/entry_response'
        cache:
          properties:
            beforeRequest:
              oneOf:
              - type: "null"
              - properties:
                  expires:
                    pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))?
                    type: string
                  lastAccess:
                    pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))?
                    type: string
                  eTag:
                    type: string
                  hitCount:
                    type: integer
                  comment:
                    type: string
                required:
                - eTag
                - hitCount
                - lastAccess
                type: object
            afterRequest:
              oneOf:
              - type: "null"
              - properties:
                  expires:
                    pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))?
                    type: string
                  lastAccess:
                    pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))?
                    type: string
                  eTag:
                    type: string
                  hitCount:
                    type: integer
                  comment:
                    type: string
                required:
                - eTag
                - hitCount
                - lastAccess
                type: object
            comment:
              type: string
        timings:
          properties:
            dns:
              minimum: -1
              type: number
            connect:
              minimum: -1
              type: number
            blocked:
              minimum: -1
              type: number
            send:
              minimum: -1
              type: number
            wait:
              minimum: -1
              type: number
            receive:
              minimum: -1
              type: number
            ssl:
              minimum: -1
              type: number
            comment:
              type: string
          required:
          - receive
          - send
          - wait
        serverIPAddress:
          oneOf:
          - format: ipv4
          - format: ipv6
          type: string
        connection:
          type: string
        comment:
          type: string
      required:
      - cache
      - request
      - response
      - startedDateTime
      - time
      - timings
      type: object
    header:
      example:
        name: name
        comment: comment
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        comment:
          type: string
      required:
      - name
      - value
      type: object
    har:
      example:
        log:
          creator:
            name: name
            comment: comment
            version: version
          entries:
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            request:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              method: method
              headersSize: 5
              bodySize: 5
              comment: comment
              queryString:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              postData: '{}'
              url: https://openapi-generator.tech
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
            cache: '{}'
            response:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              redirectURL: redirectURL
              statusText: statusText
              headersSize: 3
              bodySize: 2
              comment: comment
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              content:
                size: 7
                comment: comment
                mimeType: mimeType
                text: text
                compression: 9
                encoding: encoding
              status: 2
            serverIPAddress: serverIPAddress
            timings: '{}'
            connection: connection
            comment: comment
            time: 0.14658129805029452
            pageref: pageref
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            request:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              method: method
              headersSize: 5
              bodySize: 5
              comment: comment
              queryString:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              postData: '{}'
              url: https://openapi-generator.tech
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
            cache: '{}'
            response:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              redirectURL: redirectURL
              statusText: statusText
              headersSize: 3
              bodySize: 2
              comment: comment
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              content:
                size: 7
                comment: comment
                mimeType: mimeType
                text: text
                compression: 9
                encoding: encoding
              status: 2
            serverIPAddress: serverIPAddress
            timings: '{}'
            connection: connection
            comment: comment
            time: 0.14658129805029452
            pageref: pageref
          pages:
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            pageTimings:
              onContentLoad: -0.9199171809538988
              onLoad: -0.3972543816929597
              comment: comment
            comment: comment
            id: id
            title: title
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            pageTimings:
              onContentLoad: -0.9199171809538988
              onLoad: -0.3972543816929597
              comment: comment
            comment: comment
            id: id
            title: title
          browser:
            name: name
            comment: comment
            version: version
          comment: comment
          version: version
      properties:
        log:
          $ref: '#/components/schemas/har_log'
      required:
      - log
      type: object
    page:
      example:
        startedDateTime: 2000-01-23T04:56:07.000+00:00
        pageTimings:
          onContentLoad: -0.9199171809538988
          onLoad: -0.3972543816929597
          comment: comment
        comment: comment
        id: id
        title: title
      properties:
        startedDateTime:
          format: date-time
          pattern: ^(\d{4})(-)?(\d\d)(-)?(\d\d)(T)?(\d\d)(:)?(\d\d)(:)?(\d\d)(\.\d+)?(Z|([+-])(\d\d)(:)?(\d\d))
          type: string
        id:
          type: string
        title:
          type: string
        pageTimings:
          $ref: '#/components/schemas/page_pageTimings'
        comment:
          type: string
      required:
      - id
      - pageTimings
      - startedDateTime
      - title
      type: object
    AuthBasic:
      example:
        base_64_credentials: base_64_credentials
      properties:
        base_64_credentials:
          description: base 64 encoding of the username and password
          type: string
      required:
      - base_64_credentials
      type: object
    AllowList:
      example:
        url_pattern: url_pattern
        status_code: status_code
      properties:
        status_code:
          description: HTTP Status Code to match
          type: string
        url_pattern:
          description: URL Regex Pattern to match
          type: string
      required:
      - status_code
      - url_pattern
      type: object
    BlockList:
      example:
        url_pattern: url_pattern
        status_code: status_code
        http_method_pattern: http_method_pattern
      properties:
        status_code:
          description: HTTP Status Code
          type: string
        url_pattern:
          description: URL Regex Pattern
          type: string
        http_method_pattern:
          description: HTTP Method Regex Pattern
          type: string
      required:
      - http_method_pattern
      - status_code
      - url_pattern
      type: object
    Headers:
      example:
        headers: '{}'
      properties:
        headers:
          description: Header key-value pairs
          type: object
      required:
      - headers
      type: object
    entry_request_cookies:
      example:
        path: path
        expires: expires
        domain: domain
        name: name
        comment: comment
        httpOnly: true
        secure: true
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        path:
          type: string
        domain:
          type: string
        expires:
          type: string
        httpOnly:
          type: boolean
        secure:
          type: boolean
        comment:
          type: string
      required:
      - name
      - value
      type: object
    entry_request_queryString:
      example:
        name: name
        comment: comment
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        comment:
          type: string
      required:
      - name
      - value
      type: object
    entry_request:
      example:
        headers:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        httpVersion: httpVersion
        method: method
        headersSize: 5
        bodySize: 5
        comment: comment
        queryString:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        postData: '{}'
        url: https://openapi-generator.tech
        cookies:
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
      properties:
        method:
          type: string
        url:
          format: uri
          type: string
        httpVersion:
          type: string
        cookies:
          items:
            $ref: '#/components/schemas/entry_request_cookies'
          type: array
        headers:
          items:
            $ref: '#/components/schemas/header'
          type: array
        queryString:
          items:
            $ref: '#/components/schemas/entry_request_queryString'
          type: array
        postData:
          description: Posted data info.
          properties:
            mimeType:
              type: string
            text:
              type: string
            params:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                  fileName:
                    type: string
                  contentType:
                    type: string
                  comment:
                    type: string
                type: object
              type: array
          required:
          - mimeType
        headersSize:
          type: integer
        bodySize:
          type: integer
        comment:
          type: string
      required:
      - bodySize
      - cookies
      - headers
      - headersSize
      - httpVersion
      - method
      - queryString
      - url
      type: object
    entry_response_content:
      example:
        size: 7
        comment: comment
        mimeType: mimeType
        text: text
        compression: 9
        encoding: encoding
      properties:
        size:
          type: integer
        compression:
          type: integer
        mimeType:
          type: string
        text:
          type: string
        encoding:
          type: string
        comment:
          type: string
      required:
      - mimeType
      - size
      type: object
    entry_response:
      example:
        headers:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        httpVersion: httpVersion
        redirectURL: redirectURL
        statusText: statusText
        headersSize: 3
        bodySize: 2
        comment: comment
        cookies:
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        content:
          size: 7
          comment: comment
          mimeType: mimeType
          text: text
          compression: 9
          encoding: encoding
        status: 2
      properties:
        status:
          type: integer
        statusText:
          type: string
        httpVersion:
          type: string
        cookies:
          items:
            $ref: '#/components/schemas/entry_request_cookies'
          type: array
        headers:
          items:
            $ref: '#/components/schemas/header'
          type: array
        content:
          $ref: '#/components/schemas/entry_response_content'
        redirectURL:
          type: string
        headersSize:
          type: integer
        bodySize:
          type: integer
        comment:
          type: string
      required:
      - bodySize
      - content
      - cookies
      - headers
      - headersSize
      - httpVersion
      - redirectURL
      - status
      - statusText
      type: object
    har_log_creator:
      example:
        name: name
        comment: comment
        version: version
      properties:
        name:
          type: string
        version:
          type: string
        comment:
          type: string
      required:
      - name
      - version
      type: object
    har_log:
      example:
        creator:
          name: name
          comment: comment
          version: version
        entries:
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          request:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            method: method
            headersSize: 5
            bodySize: 5
            comment: comment
            queryString:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            postData: '{}'
            url: https://openapi-generator.tech
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
          cache: '{}'
          response:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            redirectURL: redirectURL
            statusText: statusText
            headersSize: 3
            bodySize: 2
            comment: comment
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            content:
              size: 7
              comment: comment
              mimeType: mimeType
              text: text
              compression: 9
              encoding: encoding
            status: 2
          serverIPAddress: serverIPAddress
          timings: '{}'
          connection: connection
          comment: comment
          time: 0.14658129805029452
          pageref: pageref
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          request:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            method: method
            headersSize: 5
            bodySize: 5
            comment: comment
            queryString:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            postData: '{}'
            url: https://openapi-generator.tech
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
          cache: '{}'
          response:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            redirectURL: redirectURL
            statusText: statusText
            headersSize: 3
            bodySize: 2
            comment: comment
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            content:
              size: 7
              comment: comment
              mimeType: mimeType
              text: text
              compression: 9
              encoding: encoding
            status: 2
          serverIPAddress: serverIPAddress
          timings: '{}'
          connection: connection
          comment: comment
          time: 0.14658129805029452
          pageref: pageref
        pages:
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          pageTimings:
            onContentLoad: -0.9199171809538988
            onLoad: -0.3972543816929597
            comment: comment
          comment: comment
          id: id
          title: title
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          pageTimings:
            onContentLoad: -0.9199171809538988
            onLoad: -0.3972543816929597
            comment: comment
          comment: comment
          id: id
          title: title
        browser:
          name: name
          comment: comment
          version: version
        comment: comment
        version: version
      properties:
        version:
          type: string
        creator:
          $ref: '#/components/schemas/har_log_creator'
        browser:
          $ref: '#/components/schemas/har_log_creator'
        pages:
          items:
            $ref: '#/components/schemas/page'
          type: array
        entries:
          items:
            $ref: '#/components/schemas/entry'
          type: array
        comment:
          type: string
      required:
      - creator
      - entries
      - version
      type: object
    page_pageTimings:
      example:
        onContentLoad: -0.9199171809538988
        onLoad: -0.3972543816929597
        comment: comment
      properties:
        onContentLoad:
          minimum: -1
          type: number
        onLoad:
          minimum: -1
          type: number
        comment:
          type: string
      type: object

